github: [Kerliix]
patreon: Kerliix
open_collective: kerliix
ko_fi: kerliix
tidelift: npm/kerliix-oauth
community_bridge: kerliix
liberapay: kerliix
issuehunt: kerliix
lfx_crowdfunding: kerliix
polar: kerliix
buy_me_a_coffee: kerliix
thanks_dev: kerliix
# custom: ['https://dev.kerliix.com/donate', 'https://kerliix.com/support']
